version: 0.2

phases:
  build:
    commands:
      # Étapes de build
      - echo "Commence le déploiement du site statique"
      - aws s3 sync ./s3://frontenduser/frontend.html s3://frontenduser --delete
      # Mettez à jour l'option --cache-control selon vos besoins
      - aws s3 cp s3://frontenduser s3://frontenduser --recursive --metadata-directive REPLACE --cache-control "max-age=604800, public"
  post_build:
    commands:
      # Étapes après le build
      - echo "Déploiement du site statique terminé avec succès"
