version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - npm install -g aws-cli
      - aws lambda update-function-code --function-name pipelinefunction --zip-file fileb://./buildspec.zip
      - aws lambda publish-version --function-name pipelinefunction
